- name: install apache2 and php  
  apt:
    name: 
      - apache2
      - php
      - python-mysqldb
      - php-cli
      - php-common
      - php-gd
      - php-mysql
      - php-mbstring
      - php-intl
      - php-xml
      - php-zip
      - php-pear
      - libapache2-mod-php
    state: latest

- name: Start Apache service 
  service: name=apache2 state=started enabled=yes
