- hosts: all
  remote_user: root
  become: yes
  gather_facts: false
  tasks:
  - name: Install Python
    raw: test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal) || (yum -y install python libselinux-python)

- hosts: server 
  become: yes
  roles:
    -  webserver

- hosts: db 
  become: yes
  roles:
    - database 

- hosts: server 
  become: yes
  roles:
    - wordpress 