- name: Install mysql
  apt: pkg={{ item }} state=installed
  become: true
  with_items:    
    - mysql-server
    - python-mysqldb

- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: Create mysql database
  mysql_db: name={{wp.db }} state=present
  become: yes

- name: update root password for all accounts
  mysql_user: 
    name: "{{ root.name }}"
    host: "{{ item }}"
    login_user: "{{ root.login }}"
    login_password: "{{ root.password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL"
  with_items:
    - "{{ root.host }}"
    - 127.0.0.1
    - ::1
    - localhost 
  become: yes  

- name: Create mysql wordpress user
  mysql_user: 
    name: "{{ wp.name }}"
    host: "{{ item }}"
    login_user: "{{ wp.login }}"
    login_password: "{{ wp.password }}"
    priv: "*.*:ALL"
  with_items:
    - "{{ wp.host }}"
    - 127.0.0.1
    - ::1
    - localhost 
  become: yes  