- hosts: server 
  gather_facts: false
  become: yes
  tasks:
    - name: install apache2 and php  
      apt:
        name: 
          - apache2
          - php
          - python-mysqldb
          - php-cli
          - php-common
          - php-gd
          - php-mysql
          - php-xml
          - libapache2-mod-php
        state: latest
        update_cache: true
    - name: Start Apache service 
      service: name=apache2 state=started enabled=yes

- hosts: db
  vars:
    db: wordpress
    root:
      name: root
      login: root
      password: root
      host: 192.168.56.67
    wp:
      name: wordpress
      login: wordpress
      password: wordpress
      host: 192.168.56.67
  gather_facts: false
  become: yes
  tasks:
    - name: Install mysql
      apt:
        name:
          - python3-pip
          - python-mysqldb
          - mysql-server
          - libmysqlclient-dev
        update_cache: true
        state: latest

    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: latest

    - name: Copy the root credentials as .my.cnf file
      template: 
        src: ./templates/root.cnf.j2 
        dest: ~/.my.cnf 
        mode: 0600   

    - name: Update mysql cnf file to allow remote connections
      lineinfile:
        dest=/etc/mysql/mysql.conf.d/mysqld.cnf
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
      with_items:
        - {'regexp': "bind-address", 'line': "#bind-address"}        
      
    - name: restart mysql
      service: name=mysql state=restarted

    - name : Ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: update root password for all accounts
      mysql_user:
        login_host: "{{ root.host }}"
        login_user: "{{ root.login }}"
        login_password: "{{ root.password }}"
        name: "{{ root.name }}"
        host: "{{ item }}"
        state: present
      with_items:
        - "{{ root.host }}"
        - 127.0.0.1
        - ::1
        - localhost 
        - 192.168.56.65
        - 192.168.56.66

    - name: Create mysql database
      become: yes
      mysql_db:
        login_user: "{{ root.login }}"
        login_password: "{{ root.password }}"
        name: "{{ db }}"
        state: present


    - name: Create mysql wordpress user
      mysql_user: 
        name: "{{ wp.name }}"
        host: "{{ item }}"
        password: "{{ wp.password }}"
        login_user: "{{ root.login }}"
        login_password: "{{ root.password }}"
        priv: "*.*:ALL"
      with_items:
        - "{{ wp.host }}"
        - 127.0.0.1
        - ::1
        - localhost
        - 192.168.56.65
        - 192.168.56.66
        - "%"

- hosts: server 
  become: yes
  vars:
    db: wordpress
    wp:
      name: wordpress
      login: wordpress
      password: wordpress
      host: 192.168.56.67
  gather_facts: false
  tasks:
    - name: Download WordPress
      get_url: 
        url=https://wordpress.org/latest.tar.gz 
        dest=/tmp/wordpress.tar.gz
        validate_certs=no

    - name: Extract WordPress
      unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

    - name: Update default Apache site
      lineinfile: 
        dest=/etc/apache2/sites-enabled/000-default.conf 
        regexp="(.)+DocumentRoot /var/www/html"
        line="DocumentRoot /var/www/wordpress"

    - name: restart mysql
      service: name=mysql state=restarted

    - name: Copy WordPress config file
      template: src=/templates/wp-config.php dest=/var/www/wordpress/ force=yes

