---
# Etapas do servidor database
- hosts: db
  vars:
  # Habilitar conexão entre máquinas virtuais para possível troubleshooting
    con_hosts:
    - 192.168.56.67
    - 192.168.56.66
    - 192.168.56.65
    db: wordpress
    root:
      name: root
      login: root
      password: root
    wp:
      name: wordpress
      login: wordpress
      password: wordpress
  become: yes
  become_user: root
  tasks:
    # Etapa 1 - Instalar MySQL server e dependências
    - name: install mysql
      apt:
        name:
          - mysql-server
          - python3-mysqldb
        update_cache: true
        state: latest 
    # Etapa 2 - Atualizar arquivo de autenticação client
    - name: copy the root credentials as .my.cnf file
      template:
        src: ./templates/root.cnf.j2
        dest: /root/my.cnf
        owner: root
        group: root
        mode: 0600
    # Etapa 3 - Atualizar senhas do usuário Root do MySQL
    - name: update root password for all accounts
      mysql_user:
        name: "{{ root.name }}"
        host: "{{ item }}"
        password: "{{ root.password }}"
        priv: "*.*:ALL,GRANT"
        state: present
        check_implicit_admin: yes
      with_items:
        - "{{ con_hosts }}"
        - 127.0.0.1
        - ::1
        - localhost
    # Etapa 4 - Modificar arquivo de configuração MySQL, habilitando conexões remotas 
    - name: update mysql cnf file to allow remote connections
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - {'regexp': "bind-address", 'line': "bind-address  = 0.0.0.0"}   
    # Etapa 5 - Reiniciar MySQL
    - name: restart mysql
      service:
        name: mysql
        state: restarted
    # Etapa 6 - Garantir que o MySQL está rodando
    - name : ensure mysql started
      service: 
        name: mysql
        state: started
        enabled: yes
    # Etapa 7 - Criar banco de dados Wordpress
    - name: create mysql database
      mysql_db:
        login_user: "{{ root.login }}"
        login_password: "{{ root.password }}"
        name: "{{ db }}"
        state: present
    # Etapa 8 - Criar usuário Wordpress no MySQL
    - name: create mysql wordpress user
      mysql_user:
        login_user: "{{ root.login }}"
        login_password: "{{ root.password }}"
        name: "{{ wp.name }}"
        host: "{{ item }}"
        password: "{{ wp.password }}"
        priv: "*.*:ALL"
      with_items:
        - "{{ con_hosts }}"
        - 127.0.0.1
        - ::1
        - localhost
# Etapas do servidor web
- hosts: server
  become: yes
  vars:
    db:
      name: wordpress
      host: 192.168.56.67
    wp:
      name: wordpress
      login: wordpress
      password: wordpress
  tasks:
   # Etapa 9 - Instalar Apache2 e dependências 
    - name: install apache2 and php
      apt:
        name:
          - apache2
          - php
          - python-mysqldb
          - php-cli
          - php-common
          - php-gd
          - php-mysql
          - php-xml
          - libapache2-mod-php
        state: latest
        update_cache: true
   # Etapa 10 - Iniciar e habilitar o serviço do Apache2 
    - name: start apache service
      service:
        name: apache2
        state: started
        enabled: yes
   # Etapa 11 - Download pacote Wordpress
    - name: download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        validate_certs: no
   # Etapa 12 - Extrair pacote
    - name: extract wordpress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        copy: no
   # Etapa 13 - Atualizar site padrão do Apache2
    - name: update default apache site
      lineinfile:
        dest: /etc/apache2/sites-enabled/000-default.conf
        regexp: "(.)+DocumentRoot /var/www/html"
        line: "DocumentRoot /var/www/wordpress"
   # Etapa 14 - Atualizar arquivo de configuração Wordpress
    - name: copy wordpress config file
      template:
        src: ./templates/wp-config.php
        dest: /var/www/wordpress/
        force: yes
   # Etapa 15 - Reiniciar Apache2
    - name: restart apache2
      service:
        name: apache2
        state: restarted

  