---
- hosts: server 
  become: yes
  tasks:
    - name: install apache2 and php
      apt:
        name:
          - apache2
          - php
          - python-mysqldb
          - php-cli
          - php-common
          - php-gd
          - php-mysql
          - php-xml
          - libapache2-mod-php
        state: latest
        update_cache: true
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

- hosts: db
  vars:
    con_hosts:
    - 192.168.56.67
    - 192.168.56.66
    - 192.168.56.65
    db: wordpress
    root:
      name: root
      login: root
      password: root
    wp:
      name: wordpress
      login: wordpress
      password: wordpress
  become: yes
  become_user: root
  tasks:
    - name: install mysql
      apt:
        name:
          - mysql-server
          - python3-mysqldb
        update_cache: true
        state: latest 
  
    - name: Copy the root credentials as .my.cnf file
      template:
        src: ./templates/root.cnf.j2
        dest: /root/my.cnf
        owner: root
        group: root
        mode: 0600

    - name: update root password for all accounts
      mysql_user:
        name: "{{ root.name }}"
        host: "{{ item }}"
        password: "{{ root.password }}"
        priv: "*.*:ALL,GRANT"
        state: present
        check_implicit_admin: yes
      with_items:
        - "{{ con_hosts }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Update mysql cnf file to allow remote connections
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - {'regexp': "bind-address", 'line': "bind-address  = 0.0.0.0"}

    
    - name: restart mysql
      service:
        name: mysql
        state: restarted

    - name : ensure mysql started
      service: 
        name: mysql
        state: started
        enabled: yes

    - name: create mysql database
      mysql_db:
        login_user: "{{ root.login }}"
        login_password: "{{ root.password }}"
        name: "{{ db }}"
        state: present

    - name: create mysql wordpress user
      mysql_user:
        login_user: "{{ root.login }}"
        login_password: "{{ root.password }}"
        name: "{{ wp.name }}"
        host: "{{ item }}"
        password: "{{ wp.password }}"
        priv: "*.*:ALL"
      with_items:
        - "{{ con_hosts }}"
        - 127.0.0.1
        - ::1
        - localhost

- hosts: server
  become: yes
  vars:
    db:
      name: wordpress
      host: 192.168.56.67
    wp:
      name: wordpress
      login: wordpress
      password: wordpress
  tasks:
    - name: download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        validate_certs: no

    - name: extract wordpress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        copy: no

    - name: update default apache site
      lineinfile:
        dest: /etc/apache2/sites-enabled/000-default.conf
        regexp: "(.)+DocumentRoot /var/www/html"
        line: "DocumentRoot /var/www/wordpress"

    - name: copy WordPress config file
      template:
        src: ./templates/wp-config.php
        dest: /var/www/wordpress/
        force: yes

    - name: restart apache2
      service:
        name: apache2
        state: restarted

  